from colorama import Fore, Style, Back
LINENB_COLOR = Fore.LIGHTYELLOW_EX
FILENAME_COLOR = Fore.LIGHTCYAN_EX
NORMAL = Style.NORMAL + Fore.LIGHTGREEN_EX
ERROR_COLOR = Fore.LIGHTRED_EX
MATCH_COLOR = Style.BRIGHT
